### ISSUE TITLE
sobre video-maker

### ISSUE THREAD

**Issue by megavapor** [apfjunior/video-maker#16]
que show essa mudança que vc fez ficou totalmente free, tentei seguir tutorial git filipe mas como mudou a config da api google nao consigo descobrir o que é, posso baixar o seu e tentar ver se funciona aqui? o que vou precisar é alterar os arquivos .json e o que mais nessa questao do adobe???

**Comment by apfjunior** [comment]
Vc pode fazer o fork normal ou simplesmente **git clone https://github.com/apfjunior/video-maker.git** do repositório na sua máquina.

Será necessário que você tenha configurado por conta própria esses arquivos na pasta `credentials/`. São eles:

```
algorithmia.json
google-search.json
google-youtube.json
package.json
watson-nlu.json
```

Digo "por conta própria" é que vc mesmo terá que criar uma conta na **Algorithmia**, usar **sua conta Google** e criar sua conta na **IBM**, por favor, não me entenda mal! =D

Realmente quando fiz na época, tinha mudado o uso da API Google pro projeto, mas tem as Issues do repositório oficial,  onde a galera ajudaram nessa parte. Foi por lá que consegui (tava empacado nessa parte também haha).

Sobre a questão da Adobe, quando chegou nessa parte do Filipe, fui logo pra ferramenta free e adaptei essa versão pro projeto, vendo outros projetos da comunidade e tal. Realmente não sei ate ajudar, mas galera ainda está ativa no projeto lá.

**Comment by megavapor** [comment]
> Vc pode fazer o fork normal ou simplesmente **git clone https://github.com/apfjunior/video-maker.git** do repositório na sua máquina.
> 
> Será necessário que você tenha configurado por conta própria esses arquivos na pasta `credentials/`. São eles:
> 
> ```
> algorithmia.json
> google-search.json
> google-youtube.json
> package.json
> watson-nlu.json
> ```

peguei aqui teu fork e fui conferir, só nome youtube.json que tava no tutorial felipe, vc mudou pra google-youtube.json? bom alterei pra garantir kkk o que é o package.json??? viajei aqui nao vi no tutorial esse arquivo...


> 
> Digo "por conta própria" é que vc mesmo terá que criar uma conta na **Algorithmia**, usar **sua conta Google** e criar sua conta na **IBM**, por favor, não me entenda mal! =D


imagina meu amigo fiz tudo como ta no felipe, mas acho que na api do google tem algumas configs a mais atualmente, ex uso interno ou externo, externo é limitado precisa autorizacao etc e interno nem é possivel clicar, acho que pode ser isso, sabe como testo se minha api google ta ok???


> 
> Realmente quando fiz na época, tinha mudado o uso da API Google pro projeto, mas tem as Issues do repositório oficial, onde a galera ajudaram nessa parte. Foi por lá que consegui (tava empacado nessa parte também haha).
> 
nao lembra aonde ali tem essas dicas sobre api do google, deu uma olhada por cima nao achei, tem que olhar um a um xiii rsrsrs

> Sobre a questão da Adobe, quando chegou nessa parte do Filipe, fui logo pra ferramenta free e adaptei essa versão pro projeto, vendo outros projetos da comunidade e tal. Realmente na versao com o Adobe, não sei como te ajudar, mas a comunidade ainda está ativa nesse projeto.

na realidade tua mudança é perfeita, fica tudo free correto, quero usar como vc fez

seguinte, ja programei ha muitos anos mas hj emdia nada mais, produzo conteudo, tenho um canal, e tenho algumas ideias que poderiam girar com esse robo, por isso te pergunto ai vc que acompanhou o processo, é programador, conhece alguem que ta conseguindo rodar legal esse robo, subir os videos normal e consegue monetizar??? isso é o mais importante pois ja perdi uma conta adsense por diretrizes, e é um parto pra tentar monetizar de novo, to me ferrando nisso, eles pegam tudo, automatizacao complicado spam e copy, por isso te pergunto, sinceramente o que vc acha, tipo foi mais um estudo mesmo do felipe pra ensinar programacao, mas rodar monetização complicado, qual sua opiniao?

**Comment by megavapor** [comment]
pra garantir baixei de novo teu fork, fiz instalacao npm i ok mandei rodar e mesmo erro:
a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
$ node index.js
internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: E:\videomaker\videojunior2\credentials\google-search.json: Unexpect
ed string in JSON at position 60
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\videomaker\videojunior2\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
$




esse arquivo package.json em credenciais
achei um ali no felipe nao fala nada no tutorial sobre ele
é esse abaixo codigo será?
{
  "name": "video-maker",
  "version": "1.0.0",
  "description": "Projeto open source para fazer vídeos automatizados",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/filipedeschamps/video-maker.git"
  },
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/filipedeschamps/video-maker/issues"
  },
  "homepage": "https://github.com/filipedeschamps/video-maker#readme",
  "dependencies": {
    "algorithmia": "^0.3.10",
    "express": "^4.16.4",
    "gm": "^1.23.1",
    "googleapis": "^38.0.0",
    "image-downloader": "^3.4.2",
    "readline-sync": "^1.4.9",
    "sbd": "^1.0.14",
    "watson-developer-cloud": "^3.18.2"
  }
}


adicionei e nada , mesmo erro ta dificil rsrrs

**Comment by apfjunior** [comment]
> pra garantir baixei de novo teu fork, fiz instalacao npm i ok mandei rodar e mesmo erro:
> a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
> $ node index.js
> internal/modules/cjs/loader.js:1174
> throw err;
> ^
> 
> SyntaxError: E:\videomaker\videojunior2\credentials\google-search.json: Unexpect
> ed string in JSON at position 60
> at parse ()
> at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
> at Module.load (internal/modules/cjs/loader.js:985:32)
> at Function.Module._load (internal/modules/cjs/loader.js:878:14)
> at Module.require (internal/modules/cjs/loader.js:1025:19)
> at require (internal/modules/cjs/helpers.js:72:18)
> at Object. (E:\videomaker\videojunior2\robots\image.js:6:33)
> at Module._compile (internal/modules/cjs/loader.js:1137:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
> at Module.load (internal/modules/cjs/loader.js:985:32)
> 
> a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
> $
> 
> esse arquivo package.json em credenciais
> achei um ali no felipe nao fala nada no tutorial sobre ele
> é esse abaixo codigo será?
> {
> "name": "video-maker",
> "version": "1.0.0",
> "description": "Projeto open source para fazer vídeos automatizados",
> "main": "index.js",
> "scripts": {
> "test": "echo "Error: no test specified" && exit 1"
> },
> "repository": {
> "type": "git",
> "url": "git+https://github.com/filipedeschamps/video-maker.git"
> },
> "author": "",
> "license": "ISC",
> "bugs": {
> "url": "https://github.com/filipedeschamps/video-maker/issues"
> },
> "homepage": "https://github.com/filipedeschamps/video-maker#readme",
> "dependencies": {
> "algorithmia": "^0.3.10",
> "express": "^4.16.4",
> "gm": "^1.23.1",
> "googleapis": "^38.0.0",
> "image-downloader": "^3.4.2",
> "readline-sync": "^1.4.9",
> "sbd": "^1.0.14",
> "watson-developer-cloud": "^3.18.2"
> }
> }
> 
> adicionei e nada , mesmo erro ta dificil rsrrs



> throw

Blz, vamos lá! O `package.json` basicamente é um local onde fica configurado todas as libs e suas versões que foram utilizadas  no projeto, nem é preciso mexer lá. Sabendo disso, o erro não está nesse arquivo. O erro principal é de Sintaxe (SyntaxError) no arquivo `google-search.json`, até sem nenhuma novidade hahaha. pode ser alguma vírgula ou variável escrita/colocada errada ou qualquer coisa fora desse padrão reconhecido pela API:

```
{
  "apiKey": "xxxxxxxxxxx-xxxxxxxxxxxx_xxxxxxxxx_xxxx",
  "searchEngineId": "00000000000000000000:xxxxxxxxxxx"
}
```
Como te falei, estou partindo da lógica que vc conseguiu gerar normalmente uma API lá no Google e o erro não é nem de conexão e sim de sintaxe. Copie e cole essa parte de código acima no `google-search.json`,  e subistitua a `apiKey` e `searchEngineId` com os respectivos valores gerados.

Vou fechar a outra Issue aberta e deixa apenas esta pra que eu possa tentar te ajudar melhor.

**Comment by megavapor** [comment]
show cara vamos continuar a novela kkk nao vou desistir kkk, fui la e baixei de novo o teu fork blz, fiz 
git checkout -b user-input
pra sair da master blz nao sei se ta certo isso 
dequalquer maneira fis instalacao tanto na master como user mesmos erros
npm i 
retornou isso em ambas (talvez seja isso que nao deixa depois rodar sei la):
a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior3 (master)
$ git checkout -b user-input
Switched to a new branch 'user-input'

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior3 (user-input)
$ npm i
npm WARN acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/darwin-x64@4.1.0 (node_modules\@ffmpeg-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm@4.1.3 (node_modules\@ffmpeg-installer\linux-arm):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm@4.1.3: wanted {"os":"linux","arch":"arm"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-arm64@4.1.4 (node_modules\@ffmpeg-installer\linux-arm64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-arm64@4.1.4: wanted {"os":"linux","arch":"arm64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-ia32@4.1.0 (node_modules\@ffmpeg-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/linux-x64@4.1.0 (node_modules\@ffmpeg-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffmpeg-installer/win32-ia32@4.1.0 (node_modules\@ffmpeg-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffmpeg-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/darwin-x64@4.1.0 (node_modules\@ffprobe-installer\darwin-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/darwin-x64@4.1.0: wanted {"os":"darwin","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-ia32@4.1.0 (node_modules\@ffprobe-installer\linux-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-ia32@4.1.0: wanted {"os":"linux","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/linux-x64@4.1.0 (node_modules\@ffprobe-installer\linux-x64):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/linux-x64@4.1.0: wanted {"os":"linux","arch":"x64"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @ffprobe-installer/win32-ia32@4.1.0 (node_modules\@ffprobe-installer\win32-ia32):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for @ffprobe-installer/win32-ia32@4.1.0: wanted {"os":"win32","arch":"ia32"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 1092 packages in 81.205s

30 packages are looking for funding
  run `npm fund` for details

found 4166 vulnerabilities (4162 low, 1 moderate, 3 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by megavapor** [comment]
continuando realmente faltava apenas uma virgula cara no google-search.json affffff entre key e a id pqp fora programação kkkk
agora ja andou pouco mais pediu a palavra e depois opção dai da pau no watson , bom pra garantir entrei na ibm cloud, fui la deletei as credenciais e automaticamente criou outra parecida, coloquei no watson-nlu.json e vuala, andou mais um pouco kkk agora parou no video-robot e aqui travei de novo kkkkk mas é empolgante quando anda um pouco ne, vc viu o fork do yuri que ele colocou as linguas? pt ru es jp 

segue erro:
a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior3 (user-input)
$ node index.js
Type a Wikipedia search term: bacon

[1] Whos is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 1
> [text-robot] Starting...
> [text-robot] Fetching content from Wikipedia
> [text-robot] Fetching done!
> [text-robot] Starting to fetch keywords from Watson
> [text-robot] Sentence: "Bacon is a type of salt-cured pork made from various c
uts, typically from the pork belly or from the less fatty back cuts."
> [text-robot] Keywords: pork belly, type of salt, Bacon, pork, various cuts, fa
tty back cuts

> [text-robot] Sentence: "It is eaten on its own, as a side dish , or used as a
minor ingredient to flavour dishes ."
> [text-robot] Keywords: side dish, minor ingredient, dishes

> [text-robot] Sentence: "Bacon is also used for barding and larding roasts, esp
ecially game, including venison and pheasant."
> [text-robot] Keywords: Bacon, roasts, game, venison, pheasant

> [text-robot] Sentence: "The word is derived from the Old High German bacho, me
aning "buttock", "ham" or "side of bacon", and is cognate with the Old French ba
con"
> [text-robot] Keywords: Old High German bacho, word, side of bacon, ham, Old Fr
ench bacon, buttock

> [text-robot] Sentence: "Meat from other animals, such as beef, lamb, chicken,
goat, or turkey, may also be cut, cured, or otherwise prepared to resemble bacon
, and may even be referred to as, for example, "turkey bacon"."
> [text-robot] Keywords: Meat, turkey bacon, animals, turkey, beef, lamb, chicke
n, goat, bacon, example

> [text-robot] Sentence: "Such use is common in areas with significant Jewish an
d Muslim populations as both religions prohibit the consumption of pork."
> [text-robot] Keywords: Such use, Muslim populations, areas, religions, consump
tion of pork

> [text-robot] Sentence: "Vegetarian bacons such as "soy bacon" also exist"
> [text-robot] Keywords: Vegetarian bacons, soy bacon

> [image-robot] Starting...
> [image-robot] Querying Google Images with: "bacon"
> [image-robot] Querying Google Images with: "bacon side dish"
> [image-robot] Querying Google Images with: "bacon Bacon"
> [image-robot] Querying Google Images with: "bacon Old High German bacho"
> [image-robot] Querying Google Images with: "bacon Meat"
> [image-robot] Querying Google Images with: "bacon Such use"
> [image-robot] Querying Google Images with: "bacon Vegetarian bacons"
>[image-robot] [0] [0] Image successfully downloaded: https://hips.hearstapps.co
m/hmg-prod.s3.amazonaws.com/images/delish-bacon-horizontal-1542140714.png
>[image-robot] [1] [0] Image successfully downloaded: https://homemadehooplah.co
m/wp-content/uploads/2018/10/Bacon-Beer-Cheese-Stuffing-6.jpg
>[image-robot] [2] [0] Image successfully downloaded: https://homemadehooplah.co
m/wp-content/uploads/2018/08/candied-bacon-2-1.jpg
>[image-robot] [3] [0] Image successfully downloaded: http://ecx.images-amazon.c
om/images/I/51S57WPQXSL.jpg
>[image-robot] [4] [0] Image successfully downloaded: https://observer.com/wp-co
ntent/uploads/sites/2/2019/07/gettyimages-1138250794.jpg?quality=80&strip
>[image-robot] [5] [0] Image successfully downloaded: https://www.theedgyveg.com
/wp-content/uploads/2016/05/BLOG-HEADER_RicePaperBacon_WEB.jpg
>[image-rebot] [6] [0] Error (https://www.theedgyveg.com/wp-content/uploads/2016
/05/BLOG-HEADER_RicePaperBacon_WEB.jpg: Error: Image already downloaded
>[image-robot] [6] [1] Image successfully downloaded: https://pyxis.nymag.com/v1
/imgs/290/4ef/5de4281f17b01b114631a737b65cbe4f57-05-amanda-chantal-bacon.rsquare
.w700.jpg
> [video-robot] Starting...
(node:13020) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro
Inv�lido - /content

    at ChildProcess.onExit (E:\videomaker\videojunior3\node_modules\gm\lib\comma
nd.js:301:17)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (E:\videomaker\videojunior3\node_modules\gm\node_mod
ules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:13020) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:13020) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior3 (user-input)

**Comment by apfjunior** [comment]
Isso ai! hehe

Pronto, agora pra rodar a versão do robot-video, você tem que ter instalado o `FFmpeg`. Mas vc alterou algo no `video.js`? Se sim, joga ele completo aqui.

**Comment by apfjunior** [comment]
Deu certo @megavapor ?

**Comment by megavapor** [comment]
> Deu certo @megavapor ?

dai junior blz, instalei ffmpeg e continua o erro, nao mexi nada no robo-video, exatamente o teu fork ok

> [video-robot] Starting...
(node:10720) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro
Inv�lido - /content

    at ChildProcess.onExit (E:\videomaker\videojunior2\node_modules\gm\lib\comma
nd.js:301:17)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (E:\videomaker\videojunior2\node_modules\gm\node_mod
ules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
(node:10720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:10720) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
$ ffmpeg -version
ffmpeg version 4.2.3 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 9.3.1 (GCC) 20200523
configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
libavutil      56. 31.100 / 56. 31.100
libavcodec     58. 54.100 / 58. 54.100
libavformat    58. 29.100 / 58. 29.100
libavdevice    58.  8.100 / 58.  8.100
libavfilter     7. 57.100 /  7. 57.100
libswscale      5.  5.100 /  5.  5.100
libswresample   3.  5.100 /  3.  5.100
libpostproc    55.  5.100 / 55.  5.100

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior2 (master)
$

**Comment by megavapor** [comment]
qual diferenca de executar na master ou no user-input???

**Comment by apfjunior** [comment]
> qual diferenca de executar na master ou no user-input???

Só executar na master, pois nela estão as últimas configs.  Já user-input, vai até os inputs.

No linux o FFmpeg roda tranquilo, parece que no Windows precisa configurar algumas coisas na mão. Tem esse post mostrando os passos: https://academy.streamholics.live/guias/guia-ffmpeg/ (Não sei se já fez isso).

Nessa [Issue](https://github.com/filipedeschamps/video-maker/issues/143) do projeto original, há alguns projetos similares, mas acredito que vc ainda empaque nessa parte do robot-video com ffmpeg no windows. 

Um desses projetos, foi esse [aqui](https://github.com/felvieira/video-maker) que me deu base pra fechar a minha versão. Experimenta usá-lo. Se der o mesmo erro, realmente é algo faltando na sua config do FFmpeg no Windows.

**Comment by apfjunior** [comment]
Deu certo @megavapor ?

**Comment by megavapor** [comment]
só ve se fzi certo instalei a pasta ffmpeg fiz ela path C:\ffmpeg\bin, testei no cmd de qualquer pasta executa ffmpeg blz, mas continua dando o erro no start robo video:
> [video-robot] Starting...
(node:1300) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro I
nv�lido - /content

    at ChildProcess.onExit (E:\videomaker\videojunior3\node_modules\gm\lib\comma
nd.js:301:17)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (E:\videomaker\videojunior3\node_modules\gm\node_mod
ules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:1300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:1300) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by megavapor** [comment]
copiei a pasta ffmpeg pra dentro da pasta do robo, mudou o erro:

[video-robot] Starting...
(node:7116) UnhandledPromiseRejectionWarning: Error: Command failed: Par�metro I
nv�lido - /content

    at ChildProcess.onExit (E:\videomaker\videojunior3\node_modules\gm\lib\comma
nd.js:301:17)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.cp.emit (E:\videomaker\videojunior3\node_modules\gm\node_mod
ules\cross-spawn\lib\enoent.js:40:29)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:7116) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag `--unhandle
d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 1)
(node:7116) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by renatoramospro** [comment]
Estou no processo de finalização com o After mas estou louco ja pelo uso do programa FREE então vou contribuir em breve com todos os ajustes que fiz para usar ele no Windows e fora que ainda to com a versão 7 do Windows rs

**Comment by renatoramospro** [comment]
> Isso ai! hehe
> 
> Pronto, agora pra rodar a versão do robot-video, você tem que ter instalado o `FFmpeg`. Mas vc alterou algo no `video.js`? Se sim, joga ele completo aqui.

Pelo o que eu entendi pelo os arquivos diferentes do Felipe preciso apenas substituir o antigo arquivo por esse modificado  `video.js` correto ?

**Comment by apfjunior** [comment]
Pessoal, pra quem usa o Windows, realmente é chata a configuração do FFmpeg, com todas dependências necessárias. Achei um artigo que explica como configurar um Contêiner (todo o ambiente necessário) pro FFmpeg utilizando o Docker.

(https://medium.com/coconut-stories/using-ffmpeg-with-docker-94523547f35c)

**Comment by apfjunior** [comment]
> > Isso ai! hehe
> > Pronto, agora pra rodar a versão do robot-video, você tem que ter instalado o `FFmpeg`. Mas vc alterou algo no `video.js`? Se sim, joga ele completo aqui.
> 
> Pelo o que eu entendi pelo os arquivos diferentes do Felipe preciso apenas substituir o antigo arquivo por esse modificado `video.js` correto ?

Sim.
