### ISSUE TITLE
da uma ajuda ai please

### ISSUE THREAD

**Issue by megavapor** [apfjunior/video-maker#17]
ja testei varios forks, o unico que deixou pesquisar a palavra e andou um pouco ate agora foi o do Heber , nao sei mais o que fazer, no do felipe e mais uns 2 que testei da erro antes de colocar a palavra ali, o do heber passou um pouco, da uma luz ai por favor, ja fiz de tudo, conferi as api id key etc tudo certo, vc sabe se tem alguem que conseguiu monetizar esses videos? youtube nao ta dando block em automatização?
tava tentando agora o teu aqui, como instala essas dependencias?

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/youtube-video-maker (master)
$ node index.js
Type a Wikipedia search term: ferrari

[1] Who is
[2] What is
[3] The history of
[0] CANCEL

Choose one option [1, 2, 3, 0]: 3
(node:7752) UnhandledPromiseRejectionWarning: Forbidden: Access is denied due to
invalid credentials.
at formatError (E:\videomaker\youtube-video-maker\node_modules\ibm-cloud-sdk
-core\lib\requestwrapper.js:111:17)
at E:\videomaker\youtube-video-maker\node_modules\ibm-cloud-sdk-core\lib\req
uestwrapper.js:259:19
at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:7752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). To termina
te the node process on unhandled promise rejection, use the CLI flag --unhandle d-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio
ns_mode). (rejection id: 2)
(node:7752) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
Node.js process with a non-zero exit code.

Fiz todas install das dependencias que vc falou ali mesmo assim vem esse erro:
$ node index.js
internal/modules/cjs/loader.js:1174
    throw err;
    ^

SyntaxError: E:\videomaker\videojunior\credentials\google-search.json: Unexpected s
tring in JSON at position 60
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\videomaker\videojunior\robots\image.js:6:33)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

a520@DESKTOP-85N3H1I MINGW64 /e/videomaker/videojunior (master)
$

O FORK do heber ele pede a palavra e o numero como erro inicio ok

**Comment by apfjunior** [comment]
Olhando rápido aqui, suas credenciais foram rejeitadas. Verifica se seu arquivo **algorithmia.json**, se a variávei "**apiKey**" está escrita de forma correta e se está certa sua chave gerada la no site da **Algorithmia** :
```
{
  "apiKey": "sua_Key_aqui"
}
```

Na minha época, havia muitos erros de escrita do nome dessa variável mesmo com a chave certa.

Para instalar as dependências, abra o terminal dentro do projeto ou no próprio terminal do próprio VS Code:

**`npm i`**

**Comment by megavapor** [comment]
> Olhando rápido aqui, suas credenciais foram rejeitadas. Verifica se seu arquivo **algorithmia.json**, se a variávei "**apiKey**" está escrita de forma correta e se está certa sua chave gerada la no site da **Algorithmia** :
> 
> ```
> {
>   "apiKey": "sua_Key_aqui"
> }

conferi 2 x ja kkkk, cadastrei no si dele copiei e colei ali certinho com aspas etc, mas o erro  nao é no google?
SyntaxError: E:\videomaker\videojunior\credentials\google-search.json: Unexpected s
tring in JSON at position 60
google é muito complicado, primeiro fiz um projeto só, tem a chave API ok depois google search outra key blz, dai tem Oauth pro youtube  id key esse criei mais um projeto a parte sem API key pra testar mas tb nao deu...

> ```
> 
> Na minha época, havia muitos erros de escrita do nome dessa variável mesmo com a chave certa.
> 
> Para instalar as dependências, abra o terminal dentro do projeto ou no próprio terminal do próprio VS Code:
> 
> **`npm i`**

serio só fazer isso no teu fork instala tudo que vc adicionou? nossa em outro fork nao lembro de quem, fiz uns 10 comandos um a um demora um monte

> 
> Sobre monetizar os vídeos, acho que dá sim, sem problemas. O block que o youtube te dá é de 24hrs, já levei quando testei várias vezes o robot de upload no mesmo dia. Tinha ficado preocupado também xD

te perguntei aprox isso ali na outro post, valeu mesmo, mas tenho deconfiança sobre levar block do adsense no futuro mesmo conseguindo os mil inscritos e 4khoras assistidas, queria tentar achar alguem que ta usando esse robo atualmente e conseguindo monetizar, se souber de alguem cara agradeço muito mandar para cmcshm77 gmail com

**Comment by apfjunior** [comment]
> > Olhando rápido aqui, suas credenciais foram rejeitadas. Verifica se seu arquivo **algorithmia.json**, se a variávei "**apiKey**" está escrita de forma correta e se está certa sua chave gerada la no site da **Algorithmia** :
> > ```
> > {
> >   "apiKey": "sua_Key_aqui"
> > }
> > ```
> 
> conferi 2 x ja kkkk, cadastrei no si dele copiei e colei ali certinho com aspas etc, mas o erro nao é no google?
> SyntaxError: E:\videomaker\videojunior\credentials\google-search.json: Unexpected s
> tring in JSON at position 60
> google é muito complicado, primeiro fiz um projeto só, tem a chave API ok depois google search outra key blz, dai tem Oauth pro youtube id key esse criei mais um projeto a parte sem API key pra testar mas tb nao deu...
> 
> > ```
> > 
> > Na minha época, havia muitos erros de escrita do nome dessa variável mesmo com a chave certa.
> > 
> > Para instalar as dependências, abra o terminal dentro do projeto ou no próprio terminal do próprio VS Code:
> > 
> > **`npm i`**
> > ```
> 
> serio só fazer isso no teu fork instala tudo que vc adicionou? nossa em outro fork nao lembro de quem, fiz uns 10 comandos um a um demora um monte
> 
> > Sobre monetizar os vídeos, acho que dá sim, sem problemas. O block que o youtube te dá é de 24hrs, já levei quando testei várias vezes o robot de upload no mesmo dia. Tinha ficado preocupado também xD
> 
> te perguntei aprox isso ali na outro post, valeu mesmo, mas tenho deconfiança sobre levar block do adsense no futuro mesmo conseguindo os mil inscritos e 4khoras assistidas, queria tentar achar alguem que ta usando esse robo atualmente e conseguindo monetizar, se souber de alguem cara agradeço muito mandar para cmcshm77 gmail com

Vamos acompanhar essa novela nessa Issue #16  @megavapor. Fechando esta pra te ajudar no que puder lá.
